<%@ Page Title="Help" Language="C#" MasterPageFile="~/PL/Site.Master" AutoEventWireup="true" CodeBehind="Help.aspx.cs" Inherits="BESTPATH._Help" %>

<asp:Content runat="server" ID="FeaturedContent" ContentPlaceHolderID="FeaturedContent">
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>Help</h1>
            </hgroup>
        </div>
    </section>
</asp:Content>
<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <div class="container">
    <div class="body">
        <asp:MultiView ID="MultiView1" runat="server">
            <asp:View ID="View1" runat="server">
                <span class="instructions">We're sorry you are having problems. Please review the FAQs below to see if they can resolve your problem. Otherwise, please click the continue button below to send an email to the System Administrator on the next page.</span>
                <br /><br />
                <p><b>1. Are there any time restrictions on the <i>BestPath Foundation website</i>?</b></p>
                <p>Yes, although most pages in <b><i>Focus on Purpose (FOP)</i></b> will not take you very long to complete at all. However, in order to protect your personal information as much as possible, the <b><i>BestPath Foundation website</i></b> will automatically log you out if you have been inactive for more than 2 hours (and "inactive" means that you have not clicked on a button or link). Therefore, it will be necessary for you to complete each page in no more than 2 hours, although for most pages this will be plenty of time for you to complete your work. The few pages that have been identified that could possibly take this long to complete include all eight of the Focus Experience pages and a few pages of the Marketing Documents Creation page as well. For these, we strongly recommend that you visit the Downloads page, where there are Focus Experience and Marketing Documents Creation forms that you can download to your computer and complete your work in MS Word instead, and then with the work of thinking and composing already completed, simply come back to those pages, click the refresh button in your web browser if you have stayed on any of these pages while completing your work in MS Word, and then simply copy and paste all of your answers into the corresponding textboxes on those pages.</p>
                <p><b>IMPORTANT NOTE:</b> If you have stayed on any page while completing your work in MS Word, then you will need to click the refresh button in your web browser BEFORE you start completing that page. This will ensure that you have not already been timed out.</p>
                <p><b>REMEMBER: YOU WILL ONLY HAVE 2 HOURS TO COMPLETE EACH PAGE!</b> If you do not, you will be timed out, and then have to complete it again from the beginning!</p>
                <p><b>2. How can I change my answers after submitting them?</b></p>
                <p>Please do not be concerned about changing your answers in <b><i>Focus on Purpose</i></b> after submitting them. All work in <b><i>Focus on Purpose</i></b> prior to the Marketing Documents Creation page is pre-work to prepare you for your work on those pages, and on those pages you will have the opportunity to review your past work and summarize. Furthermore, the <b><i>Focus on Purpose process</i></b> produces three marketing documents in MS Word (Statement of Value, Expanded Experience Profile (resume), and References list), which you will be able to edit as much as you like. Once you complete the Marketing Documents Creation page, these documents will be automatically generated by this website and you will be able to download them to your computer.</p>
                <p><b>3. Will I need anything for <i>Focus on Purpose</i>?</b></p>
                <p>You will need to have a recent version of MS Word (2007 or later, or 2003 with the .docx extension), in order to open and edit your marketing documents, which are generated when you complete the Marketing Documents Creation page. If you do not have a recent version of MS Word, we strongly recommend that you acquire one.</p>
                <p><b>4. I need help, what do I do?</b></p>
                <p>You have many resources available to you as you progress through the <b><i>BPF Life Purpose Development Series</i></b>. First, you can email your RUG Authorized Personal Counselor at any time from the Contact page (click on the Contact link at the top right of all pages on the <b><i>BestPath Foundation website</i></b>) for any counseling help that you might need. Next, for any technical help, you can email the System Administrator at any time from the Help page (click on the Help link at the top right). If you need anything at all as you go through this <b><i>BPF Life Purpose Development Series</i></b>, just send us an email from the Contact or Help pages, and we will respond to you as soon as we are able, typically within 24 hours. Finally, you should have your RUG Authorized Personal Counselor's phone number, which you can text or call your RUG APC at any time for any help that you might need, and they will respond to you as soon as they are able, typically within 24 hours as well.</p>
                <p><b>5. How can I convert my marketing documents to MS Word .doc or .docx file formats?</b></p>
                <p>In order to convert your marketing documents from their original .xml file format to either .doc or .docx file formats (all are MS Word file formats, and by default open with MS Word), then you can simply open each file by double-clicking it, then choose, "file" > "save as," then select where you want to save the file in the top window panes, then below that where it will read as, "file name:," name the file whatever you choose, then below that where it will read as, "save as type:," use the drop down list to select either: "Word 97-2003 document (*.doc)" or "Word document (*.docx)," then click save. Repeat this for all three of your marketing documents. You may choose to do this because the .doc and .docx file formats are simply more common and more recognizable file formats of MS Word.</p>
                <br /><br /><br />
                <br /><br /><br />
                <div class="float-right">
                    <asp:Button ID="btnContinue" runat="server" OnClick="btnContinue_Click" Text="Continue" />
                </div>
            </asp:View>
            <asp:View ID="View2" runat="server">
                <span class="instructions">For technical help, please submit the form below to send an email to the System Administrator. Or for counseling help, please visit the Contact page.</span>
                <br /><br />
                <table class="table">
                    <tr>
                        <td class="auto-style2"><b>Email address and/or Username:</b></td>
                        <td><asp:TextBox ID="TextBox1" runat="server" Width="65%" Font-Names="Arial" ForeColor="Black"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td class="auto-style2"></td>
                        <td><asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="TextBox1" ErrorMessage="Required" Font-Bold="True" Font-Size="Large" ForeColor="Red" SetFocusOnError="True">Required</asp:RequiredFieldValidator></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><asp:RegularExpressionValidator ID="RegularExpressionValidator1" runat="server" ControlToValidate="TextBox1" ErrorMessage="RegularExpressionValidator" Font-Bold="True" Font-Size="Large" ForeColor="Red" SetFocusOnError="True" ValidationExpression="\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*">Valid Email Address Required</asp:RegularExpressionValidator></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style2"><b>Date:</b></td>
                        <td><asp:TextBox ID="TextBox5" runat="server" ReadOnly="True" Width="65%" Font-Names="Arial" ForeColor="Black"></asp:TextBox></td>
                    </tr>
                    <tr>
                        <td class="auto-style2"></td>
                        <td><asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ControlToValidate="TextBox5" ErrorMessage="Required" Font-Bold="True" Font-Size="Large" ForeColor="Red" SetFocusOnError="True">Required</asp:RequiredFieldValidator></td>
                    </tr>
                    <tr>
                        <td></td>
                        <td><asp:CompareValidator ID="CompareValidator1" runat="server" ControlToValidate="TextBox5" ErrorMessage="Valid Date Required" Font-Bold="True" Font-Size="Large" ForeColor="Red" Operator="DataTypeCheck" SetFocusOnError="True" Type="Date"></asp:CompareValidator></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style3"><b>Description of problem:</b></td>
                        <td class="auto-style4"><textarea id="TextBox3" runat="server" maxLength="900" style="font-family:'Arial';color:#000000;"></textarea></td>
                    </tr>
                    <tr>
                        <td class="auto-style2"></td>
                        <td><asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="TextBox3" ErrorMessage="Required" Font-Bold="True" Font-Size="Large" ForeColor="Red" SetFocusOnError="True">Required</asp:RequiredFieldValidator></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>&nbsp;</td>
                    </tr>
                    <tr>
                        <td class="auto-style2"><asp:Button ID="btnSubmit" runat="server" OnClick="btnSubmit_Click" Text="Submit" /></td>
                        <td></td>
                    </tr>
                </table>
                <br /><br /><br />
                <br /><br /><br />
                <div class="float-right">
                    <asp:Button ID="btnContinue2" runat="server" Text="Continue" PostBackUrl="~/PL/FOP/FOP_ProgressMenu.aspx" CausesValidation="False" />
                </div>
                <br /><br />
                <asp:Label ID="lblError" runat="server" Visible="False" Font-Bold="True" Font-Size="Large" ForeColor="Red"></asp:Label>
            </asp:View>
        </asp:MultiView>
    </div>
    </div>
<noscript>
    <meta HTTP-EQUIV="REFRESH" content="0; url=http://www.bestpathfoundation.com/PL/Utilities/EnableJavascript.aspx">
</noscript>
</asp:Content>
<asp:Content ID="Content1" runat="server" contentplaceholderid="HeadContent">
    <style type="text/css">
        .body {
            font-family: "Segoe UI";
            font-size: large;
            color: black;
            line-height: 140%;
        }
        .instructions {
            font-family: "Segoe UI";
            font-size: x-large;
            color: black;
            line-height: 140%;
            font-weight: bold;
            text-decoration: underline;
        }
        .instructions2 {
            font-family: "Segoe UI";
            font-size: x-large;
            color: black;
            line-height: 140%;
            font-weight: bold;
        }
        .table {
            width: 100%;
        }
        .auto-style2 {
            width: 25%;
        }
        textarea {
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
            width: 75%;
            height: 100%
        }
        .auto-style3 {
            width: 25%;
            height: 150px;
        }
        .auto-style4 {
            height: 150px;
        }
    </style>
</asp:Content>

